<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FsCheck.Xunit.v3" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <ProjectReference Include="..\..\src\Freeside.Core\Freeside.Core.csproj" />
  </ItemGroup>

</Project>
